name: Geth Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Install gomobile
        run: go install golang.org/x/mobile/cmd/gomobile@latest
      - name: Run geth tests
        run: make test
